"""Alembic environment.

Migrations here are **hand-written, not autogenerated**, and `target_metadata`
is None on purpose. Bhoomi describes its tables in raw SQL (PLAN.md 6) rather
than in SQLAlchemy models, because the columns that matter most are PostGIS
ones -- `GEOMETRY(Polygon, 4326)`, a GIST index -- that autogenerate cannot see
without a further dependency, and would happily propose dropping. Keeping the
migrations literal means PLAN.md 6 stays the single description of the schema
and a migration can be read against it line by line.
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import create_engine

# The repo root, so `backend.db.engine` imports when alembic is run from it.
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from backend.db.engine import ENV_VAR, database_url, normalize_url  # noqa: E402

config = context.config
if config.config_file_name is not None:
    # disable_existing_loggers=False, against fileConfig's default. Alembic is
    # normally its own process, where the default is harmless -- but migrations
    # also run in-process (the test fixture, and any future admin endpoint),
    # and there the default silently switches off every logger configured
    # before this line, including the application's own. A migration must not
    # be able to turn off logging as a side effect.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = None


def _url() -> str:
    url = config.get_main_option("sqlalchemy.url", None) or database_url()
    if not url:
        raise SystemExit(
            f"No database configured. Set {ENV_VAR} (or pass -x url=...) before "
            f"running migrations."
        )
    return normalize_url(url)


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of connecting -- `alembic upgrade head --sql`."""
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_url(), future=True)
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
